responses:
  200:
    description: IDM returned OK
  400:
    description: IDM returned Bad Request
  401:
    description: IDM returned Unauthorized
  500:
    description: Internal server error
    body:
      text/plain: