#%RAML 1.0

title: IDM Connect API
version: v1.0

types:
  contract: !include contract.json
  contracts: !include contracts.json
  bulk-delete-request: !include bulk-delete-request.json
  bulk-delete-response: !include bulk-delete-response.json
  errors: !include raml-util/schemas/errors.schema

traits:
  language: !include raml-util/traits/language.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/idm-connect:
  /contract:
    get:
      is: [
        searchable: {description: "", example: ""},
        pageable
      ]
    post:
      is: [validate]
    type:
      collection:
        schemaCollection: contracts
        schemaItem: contract
        exampleCollection: !include examples/contracts.json
        exampleItem: !include examples/contract.json
    /{id}:
      put:
        is: [ validate ]
        responses:
          409:
            description: "Conflict"
            body:
              text/plain:
                example: "Optimistic locking version has changed"
      type:
        collection-item:
          schema: contract
          exampleItem: !include examples/contract.json
    /bulk-delete:
      description: Delete multiple walk-in contracts
      post:
        is: [ validate ]
        body:
          application/json:
            type: bulk-delete-request
        responses:
          200:
            description: Request successful
            body:
              application/json:
                type: bulk-delete-response
          400:
            description: Bad request
            body:
              text/plain:
          500:
            description: Internal server error
            body:
              text/plain:

  /searchidm:
    description: Query external IDM system for existing users
    get:
      queryParameters:
        firstname:
          description: Users first name
          example: John
        lastname:
          description: Users last name
          example: Doe
        dateOfBirth:
          description: Users date of birth
          example: 2015-12-24
      responses:
        200:
          description: IDM returned OK
          body:
            application/json:
        400:
          description: IDM returned Bad Request
          body:
            application/json:
        401:
          description: IDM returned Unauthorized
          body:
            application/json:
        500:
          description: Internal server error
          body:
            text/plain: